name = "when-are-we-playing"
main = "src/app/layout.tsx"
compatibility_date = "2024-05-23"

# Optional: Specify the account ID (find in your Cloudflare dashboard)
# account_id = "your_account_id_here"

# Optional: Specify the environment (e.g., production, staging)
# [env.production]
# name = "when-are-we-playing-prod"

# Optional: Add routes if deploying to a custom domain
# routes = [
#   "yourdomain.com/*"
# ]

# Optional: KV namespaces
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "your_kv_namespace_id"

# Optional: Durable Objects
# [[durable_objects.bindings]]
# name = "MY_OBJECT"
# class_name = "MyDurableObject"

# Optional: Usage model (bundled or unbound)
# usage_model = "bundled"

# Optional: Minify output
# minify = true

# Optional: Specify build command if using a bundler
# [build]
# command = "npm run build"
# cwd = "./"
# watch_dir = "./src"